return {
  {
    name = "perl",
    keywords = { "perl" },
    docs = { "README.md", "docs/ARCHITETTURA.md" },
    commands = { "CriticaPerl", "EseguiTest", "PerlTidyFile", "PerlPodCheck" },
    modules = { "perl.toolchain" },
    files = { "lua/perl/toolchain.lua", "lua/plugins/perl.lua" },
  },
  {
    name = "database",
    keywords = { "postgresql", "dadbod", "database" },
    docs = { "README.md", "docs/ARCHITETTURA.md" },
    commands = { "ApriDatabase", "QueryDatabase" },
    modules = { "database.config" },
    files = { "lua/database/config.lua", "lua/plugins/database.lua" },
  },
  {
    name = "clips",
    keywords = { "clips" },
    docs = { "README.md", "docs/CLIPS.md", "AGENTS.md" },
    commands = { "CLIPSCheck", "CLIPSEsegui", "CLIPSPerlXSCheck", "CLIPSPerlXSTest" },
    modules = { "expert.clips" },
    files = { "lua/expert/clips.lua", "syntax/clips.vim", "after/ftplugin/clips.lua" },
  },
  {
    name = "ai",
    keywords = { "ai", "agent" },
    docs = { "README.md", "docs/AI_WORKFLOW.md", "AGENTS.md" },
    commands = { "AIStato", "AIContesto", "AIPolicy", "AIPromptCLIPS" },
    modules = { "ai.context", "ai.prompts", "utils.ai" },
    files = { "lua/ai/context.lua", "lua/ai/prompts.lua", ".aiignore" },
  },
  {
    name = "telemetry",
    keywords = { "telemetria", "risorse", "statusline", "dashboard", "sistema" },
    docs = { "README.md", "docs/UI_STYLE.md" },
    commands = { "Sistema", "Risorse", "Rete" },
    modules = { "utils.telemetry" },
    files = { "lua/utils/telemetry.lua", "lua/ui/statusline.lua", "lua/ui/dashboard.lua" },
  },
  {
    name = "macports",
    keywords = { "macports" },
    docs = { "README.md", "docs/ARCHITETTURA.md" },
    files = { "ports.txt", "scripts/ensure_macports.sh", "scripts/macos-askpass.sh", "scripts/macports-env.sh" },
  },
  {
    name = "treesitter",
    keywords = { "treesitter", "nvim-treesitter", "tree-sitter" },
    docs = { "README.md", "docs/ARCHITETTURA.md" },
    modules = { "languages.treesitter" },
    files = { "lua/languages/treesitter.lua", "lua/plugins/editor.lua" },
  },
}
