local perl = require("perl.toolchain")
local health = require("core.health")
local ide = require("ide.actions")
local telemetry = require("utils.telemetry")
local ai_context = require("ai.context")
local ai = require("utils.ai")

local function command(name, rhs, opts)
  vim.api.nvim_create_user_command(name, rhs, opts or {})
end

command("ApriProgetto", "Neotree filesystem reveal left")
command("CercaFile", "Telescope find_files")
command("CercaTesto", "Telescope live_grep")
command("CercaSimboli", ide.symbols)
command("CercaSimboliWorkspace", ide.workspace_symbols)
command("PaletteComandi", ide.command_palette)
command("Formato", function() require("conform").format({ async = true, lsp_format = "fallback" }) end)
command("CriticaPerl", perl.critic_file)
command("EseguiTest", perl.prove_file)
command("EseguiTuttiTest", perl.prove_all)
command("PerlProveFile", perl.prove_file)
command("PerlProveAll", perl.prove_all)
command("PerlCriticFile", perl.critic_file)
command("PerlTidyFile", perl.tidy_file)
command("PerlImports", perl.imports_file)
command("PerlPodCheck", perl.pod_check)
command("PerlPodPreview", perl.pod_preview)
command("PerlNYTProf", perl.nytprof)
command("CartonInstall", perl.carton_install)
command("CPANInstalla", perl.cpanm_module)
command("PerlRegex", perl.regex_scratch)
command("PerlStacktrace", perl.stacktrace_to_quickfix)
command("ApriDatabase", "DBUI")
command("QueryDatabase", "DB")
command("DebugAvvia", "DapContinue")
command("DebugStop", "DapTerminate")
command("Task", ide.tasks)
command("EseguiTask", ide.run_task)
command("Outline", ide.outline)
command("Todo", ide.todo)
command("Audit", ide.audit)
command("UndoAlbero", ide.undo)
command("RestClient", ide.rest_scratch)
command("RestEsegui", ide.rest_run)
command("Focus", "ZenMode")
command("GitStato", "Git")
command("GitDiff", "Gdiffsplit")
command("Terminale", "ToggleTerm")
command("TerminaleTmux", function()
  vim.cmd("terminal tmux new-session -A -s nvim-gp")
end)
command("Documentazione", "Telescope help_tags")
command("Workspace", "SessionSearch")
command("Salute", health.report)
command("Sistema", telemetry.panel)
command("Rete", function()
  vim.notify(telemetry.status_net(), vim.log.levels.INFO)
end)
command("Risorse", function()
  local data = telemetry.snapshot()
  vim.notify("CPU " .. data.load .. " · RAM " .. data.ram .. " · uptime " .. data.uptime, vim.log.levels.INFO)
end)
command("AIStato", function()
  vim.notify(ai.status(), vim.log.levels.INFO)
end)
command("AIContesto", ai_context.write)
command("AIPolicy", ai_context.policy_buffer)
command("AIPromptReview", function()
  ai_context.prompt_buffer("review")
end)
command("AIPromptPerformance", function()
  ai_context.prompt_buffer("performance")
end)
command("AIPromptPerl", function()
  ai_context.prompt_buffer("perl")
end)
command("AIPromptSicurezza", function()
  ai_context.prompt_buffer("sicurezza")
end)
